// System-wide constants

export const SURVEY_TYPES = {
    PICK_N: 'PICK_N',
    PRIORITY: 'PRIORITY',
    WORKFLOW_RELAY: 'WORKFLOW_RELAY',
    CALENDAR_SLOT: 'CALENDAR_SLOT',
    ACTION_PLAN_BOOKING: 'ACTION_PLAN_BOOKING',
    VERIFICATION: 'VERIFICATION',
    AUTHENTICATION: 'AUTHENTICATION'
};

export const USER_ROLES = {
    STUDENT: 'STUDENT',
    FACULTY: 'FACULTY',
    ADMIN: 'ADMIN'
};

export const PARTICIPATION_STATES = {
    ELIGIBLE: 'ELIGIBLE',
    INELIGIBLE: 'INELIGIBLE',
    VIEWING: 'VIEWING',
    HOLD_ACTIVE: 'HOLD_ACTIVE',
    SUBMITTED: 'SUBMITTED',
    PENDING_APPROVAL: 'PENDING_APPROVAL',
    APPROVED: 'APPROVED',
    REJECTED: 'REJECTED',
    ALLOCATED: 'ALLOCATED',
    WAITLISTED: 'WAITLISTED'
};

export const RELEASE_STATUSES = {
    DRAFT: 'DRAFT',
    ACTIVE: 'ACTIVE',
    PAUSED: 'PAUSED',
    CLOSED: 'CLOSED',
    ARCHIVED: 'ARCHIVED'
};

export const APPROVAL_STATUSES = {
    PENDING: 'PENDING',
    IN_PROGRESS: 'IN_PROGRESS',
    APPROVED: 'APPROVED',
    REJECTED: 'REJECTED'
};

export const DOCUMENT_STATES = {
    UPLOADED: 'UPLOADED',
    PENDING_VERIFICATION: 'PENDING_VERIFICATION',
    VERIFIED: 'VERIFIED',
    REJECTED: 'REJECTED'
};

export const HOLD_STATUSES = {
    ACTIVE: 'ACTIVE',
    CONVERTED: 'CONVERTED',
    EXPIRED: 'EXPIRED',
    RELEASED: 'RELEASED'
};

export const WAITLIST_STATUSES = {
    WAITING: 'WAITING',
    NOTIFIED: 'NOTIFIED',
    CONVERTED: 'CONVERTED',
    EXPIRED: 'EXPIRED'
};

export const ELIGIBILITY_DECISIONS = {
    ALLOW: 'ALLOW',
    DENY: 'DENY',
    ALLOW_WITH_REQUIREMENTS: 'ALLOW_WITH_REQUIREMENTS',
    WAITLIST: 'WAITLIST',
    ROUTE: 'ROUTE'
};

export const SEAT_HOLD_DURATION_MINUTES = parseInt(
    process.env.SEAT_HOLD_DURATION_MINUTES || '15'
);

export const MAX_FILE_SIZE = parseInt(
    process.env.MAX_FILE_SIZE || '10485760' // 10MB
);

export const ALLOWED_FILE_TYPES = (
    process.env.ALLOWED_FILE_TYPES || 'image/jpeg,image/png,application/pdf'
).split(',');

export default {
    SURVEY_TYPES,
    USER_ROLES,
    PARTICIPATION_STATES,
    RELEASE_STATUSES,
    APPROVAL_STATUSES,
    DOCUMENT_STATES,
    HOLD_STATUSES,
    WAITLIST_STATUSES,
    ELIGIBILITY_DECISIONS,
    SEAT_HOLD_DURATION_MINUTES,
    MAX_FILE_SIZE,
    ALLOWED_FILE_TYPES
};
